language: go

go:
 - 1.8

install:
 - go get -v github.com/Masterminds/glide
 - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/0.13.2 && go install && cd - 
 - glide install

script:
 - go test -v
